apiVersion: apps/v1
kind: Deployment
metadata:
  name: toy-blog
  labels:
    app: toy-blog
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toy-blog
      tier: app
  template:
    metadata:
      labels:
        app: toy-blog
        tier: app
    spec:
      containers:
      - name: toy-blog
        image: toy-blog
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
