apiVersion: v1
kind: Service
metadata:
  name: toy-blog-external
  labels:
    app: toy-blog
    tier: app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: toy-blog
    tier: app
