version: "3.4"

services:
  toy-blog:
    image: toy-blog
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 src/manage.py runserver 0.0.0.0:8080 --nothreading --noreload",
      ]
    ports:
      - 8080:8080
      - 5678:5678
